name: Test Custom Action
on:
  push:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run custom action
        uses: ./
        with:
          overleaf_url: 'https://www.overleaf.com/read/nsgsskwncdmy#a859ac'
          github_token: ${{ secrets.GITHUB_TOKEN }}
