name: Test
on: [push, workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      # Uses action.yml in the root directory
      - uses: ./
        with:
          overleaf_url: 'https://www.overleaf.com/read/nsgsskwncdmy#a859ac'
          github_token: ${{ secrets.GITHUB_TOKEN }}
